

# ═══════════════════════════════════════════════
# 服务注册表 (SERVICE_REGISTRY)
# ═══════════════════════════════════════════════

SERVICE_REGISTRY = {
    "company_registration": {
        "name": "公司注册",
        "description": "全国有限责任公司设立。核名 -> 材料准备 -> 工商提交 -> 执照领取，全流程代办。法人无需到场，e签宝远程签名。",
        "status": "live",
        "schema_model": CompanyRegistrationParams,
        "estimated_days": "7-14",
        "price_range": "699-1299",
        "required_documents": [
            "公司备选名称（至少3个）",
            "全体股东身份证复印件",
            "股东出资比例及出资方式",
            "经营范围描述",
            "注册地址产权证明/租赁合同",
            "法定代表人、执行董事、监事任职信息",
            "全体股东实名认证（工商App）",
        ],
        "capabilities": CAPABILITIES_COMPANY_REGISTRATION,
        "workflow_steps": [
            {"step_id": "name_reservation", "name": "核名", "order": 1, "agent_auto": True},
            {"step_id": "shareholder_info", "name": "股东信息", "order": 2, "agent_auto": True},
            {"step_id": "legal_representative", "name": "法定代表人信息", "order": 3, "agent_auto": True},
            {"step_id": "registered_capital", "name": "注册资本", "order": 4, "agent_auto": True},
            {"step_id": "registered_address", "name": "注册地址", "order": 5, "agent_auto": True},
            {"step_id": "business_scope", "name": "经营范围", "order": 6, "agent_auto": True},
            {"step_id": "articles_of_association", "name": "公司章程", "order": 7, "agent_auto": True},
            {"step_id": "document_generation", "name": "文书生成", "order": 8, "agent_auto": True},
            {"step_id": "e_sign_submission", "name": "e签宝递交", "order": 9, "agent_auto": False, "external_service": "e签宝"},
            {"step_id": "governance_review", "name": "工商局审核", "order": 10, "agent_auto": False},
            {"step_id": "license_collection", "name": "执照领取", "order": 11, "agent_auto": False},
        ],
    },
    "high_tech_application": {
        "name": "高新技术企业认定",
        "description": "国家级高新技术企业认定全流程。评分预评估 → 差距分析 → 知识产权准备 → 研发费用归集 → 申报材料撰写 → 提交 → 专家评审 → 认定。企业所得税减按15%征收。",
        "status": "live",
        "schema_model": HighTechApplicationParams,
        "estimated_days": "6-12个月",
        "price_range": "8000-30000",
        "required_documents": [
            "企业营业执照副本",
            "近三年年度审计报告",
            "近三年研发费用专项审计报告",
            "近一年高新技术产品收入专项审计报告",
            "知识产权证书（专利/软著/集成电路布图）",
            "研发人员名单及学历证明",
            "研发管理制度文件",
        ],
        "capabilities": CAPABILITIES_HIGH_TECH,
        "workflow_steps": [
            {"step_id": "score_evaluation", "name": "评分预评估", "order": 1, "agent_auto": True},
            {"step_id": "gap_analysis", "name": "差距分析", "order": 2, "agent_auto": True},
            {"step_id": "ip_preparation", "name": "知识产权准备", "order": 3, "agent_auto": False},
            {"step_id": "rd_expense_sorting", "name": "研发费用归集", "order": 4, "agent_auto": False},
            {"step_id": "material_writing", "name": "申报材料撰写", "order": 5, "agent_auto": False},
            {"step_id": "submit_and_follow", "name": "提交及跟进", "order": 6, "agent_auto": False},
            {"step_id": "expert_review", "name": "专家评审", "order": 7, "agent_auto": False},
            {"step_id": "certificate_receive", "name": "证书领取", "order": 8, "agent_auto": False},
        ],
    },
    "ip_application": {
        "name": "专利/软著申请",
        "description": "发明专利、实用新型、外观设计、软著申请全流程。查新 -> 撰写 -> 提交 -> 审查答复 -> 授权领证。",
        "status": "live",
        "schema_model": IPApplicationParams,
        "estimated_days": "视类型而定（发明18-36个月，实用新型6-12个月，外观4-8个月，软著30-60个工作日）",
        "price_range": "按需定价（发明专利4500-8000，实用新型2500-4000，外观1500-2500，软著800-1500）",
        "required_documents": [
            "技术交底书（含技术领域、背景技术、发明内容、有益效果、具体实施方式）",
            "已有的在先申请文件（如有优先权要求）",
            "发明人身份证复印件",
            "申请人营业执照或身份证复印件",
            "图纸/流程图（如有）",
            "源程序代码摘录（软著申请）",
            "用户手册（软著申请）",
        ],
        "capabilities": CAPABILITIES_IP,
        "workflow_steps": [
            {"step_id": "technical_disclosure", "name": "技术交底", "order": 1, "agent_auto": True},
            {"step_id": "prior_art_search", "name": "查新检索", "order": 2, "agent_auto": True},
            {"step_id": "patent_drafting", "name": "专利撰写", "order": 3, "agent_auto": False, "human_role": "专利代理人"},
            {"step_id": "document_review", "name": "文件确认", "order": 4, "agent_auto": True},
            {"step_id": "submission", "name": "提交申请", "order": 5, "agent_auto": False, "external_service": "专利电子申请系统/版权中心"},
            {"step_id": "examination", "name": "审查阶段", "order": 6, "agent_auto": False, "human_role": "专利代理人"},
            {"step_id": "grant_or_reject", "name": "授权/驳回", "order": 7, "agent_auto": True},
        ],
    },
    "import_export": {
        "name": "进出口备案",
        "description": "进出口权全套备案服务。对外贸易经营者备案 -> 海关注册 -> 电子口岸IC卡 -> 外汇管理局名录登记 -> 出口退税备案（可选）。一口接入，全流程代办。",
        "status": "live",
        "schema_model": ImportExportParams,
        "estimated_days": "7-15",
        "price_range": "800-2500",
        "required_documents": [
            "营业执照副本",
            "公司章程",
            "公司中英文名称及英文地址",
            "法定代表人身份证",
            "海关业务联系人身份证",
            "公司电话及邮箱",
            "主要进出口产品类别说明",
        ],
        "capabilities": CAPABILITIES_IE,
        "workflow_steps": [
            {"step_id": "materials_check", "name": "材料核验", "order": 1, "agent_auto": True},
            {"step_id": "foreign_trade_filing", "name": "外贸经营者备案", "order": 2, "agent_auto": False},
            {"step_id": "customs_registration", "name": "海关注册登记", "order": 3, "agent_auto": False},
            {"step_id": "ic_card", "name": "电子口岸IC卡", "order": 4, "agent_auto": False},
            {"step_id": "foreign_exchange", "name": "外管局名录登记", "order": 5, "agent_auto": False},
            {"step_id": "tax_refund_filing", "name": "出口退税备案", "order": 6, "agent_auto": False, "optional": True},
        ],
    },
    "legal_consulting": {
        "name": "法律咨询",
        "description": "AI初筛+专业律师终审。合同审查、协议起草、纠纷咨询、劳动人事、知识产权、合规、投融资等。AI免费初筛后匹配对口专业律师。",
        "status": "live",
        "schema_model": LegalConsultingParams,
        "estimated_days": "1-3（AI初筛即时出结果，律师意见1-3个工作日）",
        "price_range": "200-30000",
        "required_documents": [
            "问题/案情详细描述",
            "相关合同/协议（如有）",
            "对方当事人信息（如有）",
            "已有法律文书（如有）",
        ],
        "capabilities": CAPABILITIES_LEGAL,
        "workflow_steps": [
            {"step_id": "ai_initial_analysis", "name": "AI初筛", "order": 1, "agent_auto": True},
            {"step_id": "lawyer_matching", "name": "律师匹配", "order": 2, "agent_auto": True},
            {"step_id": "lawyer_consultation", "name": "律师咨询", "order": 3, "agent_auto": False},
            {"step_id": "delivery", "name": "交付意见", "order": 4, "agent_auto": False},
        ],
    },
    "accounting": {
        "name": "代理记账",
        "description": "智能代理记账服务。票据OCR识别→AI自动做账→人工复核→智能申报。小规模99元/月，一般纳税人199元/月。全流程透明可追溯。",
        "status": "live",
        "schema_model": AccountingParams,
        "estimated_days": "持续服务（按月）",
        "price_range": "99/月",
        "required_documents": [
            "营业执照副本",
            "银行开户许可证",
            "税务登记证（或已完成税务登记）",
            "法人/财务负责人身份证",
            "上一期财务报表（如有）",
            "税控盘/UKey信息",
            "每月票据/发票",
        ],
        "capabilities": CAPABILITIES_ACCOUNTING,
        "workflow_steps": [
            {"step_id": "contract_signing", "name": "签约", "order": 1, "agent_auto": True},
            {"step_id": "data_handover", "name": "数据交接", "order": 2, "agent_auto": True},
            {"step_id": "initial_setup", "name": "账套初始化", "order": 3, "agent_auto": False},
            {"step_id": "monthly_receipt_collection", "name": "每月收集票据", "order": 4, "agent_auto": False},
            {"step_id": "ocr_and_ledger", "name": "OCR+AI做账", "order": 5, "agent_auto": True},
            {"step_id": "manual_review", "name": "人工复核", "order": 6, "agent_auto": False},
            {"step_id": "tax_filing", "name": "纳税申报", "order": 7, "agent_auto": True},
            {"step_id": "report_delivery", "name": "报表交付", "order": 8, "agent_auto": True},
        ],
    },
    "tax_registration": {
        "name": "税务登记",
        "description": "企业税务登记全流程代办。税种核定 -> 纳税人类型选择（小规模/一般纳税人） -> 发票申领 -> 税务UKey申请 -> 三方扣税协议签订。AI智能推荐最优纳税人类型。",
        "status": "live",
        "schema_model": TaxRegistrationParams,
        "estimated_days": "5-10",
        "price_range": "199",
        "required_documents": [
            "营业执照正副本原件",
            "公章",
            "法定代表人身份证原件",
            "财务负责人身份证原件",
            "办税人身份证原件",
            "银行开户许可证/基本户信息",
            "经营地址证明材料",
            "公司章程复印件",
        ],
        "capabilities": CAPABILITIES_TAX_REGISTRATION,
        "workflow_steps": [
            {"step_id": "form_prefill", "name": "自动预填表单", "order": 1, "agent_auto": True},
            {"step_id": "taxpayer_analysis", "name": "纳税人类型推荐", "order": 2, "agent_auto": True},
            {"step_id": "document_preparation", "name": "材料准备", "order": 3, "agent_auto": True},
            {"step_id": "bureau_submit", "name": "税务局提交", "order": 4, "agent_auto": False},
            {"step_id": "tax_type_assessment", "name": "税种核定", "order": 5, "agent_auto": False},
            {"step_id": "invoice_quota", "name": "发票限额核定", "order": 6, "agent_auto": False},
            {"step_id": "ukey_pickup", "name": "UKey领取", "order": 7, "agent_auto": False},
            {"step_id": "agreement_signing", "name": "三方扣税协议", "order": 8, "agent_auto": True},
        ],
    },
    "bank_account": {
        "name": "银行开户",
        "description": "企业银行开户全流程代办。AI智能推荐银行 -> 预约 -> 材料准备 -> 上门核实 -> 账户激活。法人无需到场可选招行/平安上门核实或网商/微众全程在线。",
        "status": "live",
        "schema_model": BankAccountParams,
        "estimated_days": "5-10",
        "price_range": "299",
        "required_documents": [
            "营业执照正副本原件",
            "公章、财务章、法人章",
            "法定代表人身份证原件",
            "公司章程",
            "经营场地证明材料（租赁合同/产权证）",
            "股东会决议（开户）",
            "预留印鉴卡（银行提供）",
            "网银管理员身份证（如需）",
        ],
        "capabilities": CAPABILITIES_BANK_ACCOUNT,
        "workflow_steps": [
            {"step_id": "bank_recommendation", "name": "AI智能推荐银行", "order": 1, "agent_auto": True},
            {"step_id": "appointment", "name": "预约办理", "order": 2, "agent_auto": True},
            {"step_id": "document_preparation", "name": "材料准备", "order": 3, "agent_auto": True},
            {"step_id": "on_site_visit", "name": "上门核实/现场办理", "order": 4, "agent_auto": False},
            {"step_id": "account_activation", "name": "账户激活", "order": 5, "agent_auto": False},
            {"step_id": "online_banking", "name": "网银开通", "order": 6, "agent_auto": False},
        ],
    },
    "license_application": {
        "name": "资质代办",
        "description": "企业资质许可证代办。ICP许可证、食品经营许可证、医疗器械经营备案、文网文、出版物、卫生许可、道路运输、劳务派遣、人力资源服务、危化品许可、广播电视制作等12+类资质。全流程代办。",
        "status": "live",
        "schema_model": LicenseApplicationParams,
        "estimated_days": "视资质类型而定（20-90天）",
        "price_range": "599",
        "required_documents": [
            "营业执照正副本",
            "法定代表人身份证",
            "公司章程",
            "经营场所证明（租赁合同/产权证）",
            "专业人员资质证明（视资质类型）",
            "验资报告（如需）",
            "行业主管部门前置审批文件（如有）",
        ],
        "capabilities": CAPABILITIES_LICENSE_APPLICATION,
        "workflow_steps": [
            {"step_id": "requirement_analysis", "name": "资质条件分析", "order": 1, "agent_auto": True},
            {"step_id": "gap_assessment", "name": "差距评估", "order": 2, "agent_auto": True},
            {"step_id": "material_preparation", "name": "材料准备", "order": 3, "agent_auto": False},
            {"step_id": "submission", "name": "提交审批", "order": 4, "agent_auto": False},
            {"step_id": "review", "name": "审批跟进", "order": 5, "agent_auto": False},
            {"step_id": "certificate_delivery", "name": "证书交付", "order": 6, "agent_auto": False},
        ],
    },
    "trademark": {
        "name": "商标注册",
        "description": "商标注册全流程。查新检索 -> 尼斯分类推荐 -> 申请材料准备 -> 商标局提交 -> 审查跟进 -> 异议应对 -> 领证。支持新申请/续展/转让/变更/异议。覆盖45个国际分类。",
        "status": "live",
        "schema_model": TrademarkParams,
        "estimated_days": "6-12个月（新申请）",
        "price_range": "299/类",
        "required_documents": [
            "商标图样（800x800以上JPG/PDF）",
            "营业执照副本扫描件",
            "法人/申请人身份证扫描件",
            "商标注册申请书（系统生成）",
            "商标代理委托书（系统生成）",
            "优先权证明文件（如有）",
        ],
        "capabilities": CAPABILITIES_TRADEMARK,
        "workflow_steps": [
            {"step_id": "search", "name": "商标查新", "order": 1, "agent_auto": True},
            {"step_id": "class_recommendation", "name": "分类推荐", "order": 2, "agent_auto": True},
            {"step_id": "document_preparation", "name": "材料生成", "order": 3, "agent_auto": True},
            {"step_id": "submission", "name": "商标局提交", "order": 4, "agent_auto": False},
            {"step_id": "examination", "name": "审查跟进", "order": 5, "agent_auto": False},
            {"step_id": "objection_handling", "name": "异议应对", "order": 6, "agent_auto": False},
            {"step_id": "certificate_receipt", "name": "领证", "order": 7, "agent_auto": False},
        ],
    },
    "company_change": {
        "name": "工商变更",
        "description": "工商登记变更全流程。法人变更、股东变更、经营范围变更、注册资本变更（含增/减资）、地址变更（含跨区迁址）、名称变更、高管变更、章程备案、联络人员变更。AI自动生成决议和章程修正案，e签宝远程签署。",
        "status": "live",
        "schema_model": CompanyChangeParams,
        "estimated_days": "3-7（一般变更）/ ~60（减资含公告期）/ 7-15（跨区迁址）",
        "price_range": "399",
        "required_documents": [
            "营业执照正副本原件",
            "公章",
            "原法定代表人身份证（法人变更）",
            "新法定代表人身份证及手机号（法人变更）",
            "股东会决议（系统生成）",
            "章程修正案（系统生成）",
            "股权转让协议（股权变更）",
            "新地址产权证明/租赁合同（地址变更）",
            "新股东身份证/执照（股东变更）",
            "减资公告证明（减资场景）",
        ],
        "capabilities": CAPABILITIES_COMPANY_CHANGE,
        "workflow_steps": [
            {"step_id": "change_analysis", "name": "变更分析", "order": 1, "agent_auto": True},
            {"step_id": "document_generation", "name": "文书生成", "order": 2, "agent_auto": True},
            {"step_id": "document_review", "name": "内部复核", "order": 3, "agent_auto": True},
            {"step_id": "signing", "name": "签署文件", "order": 4, "agent_auto": False},
            {"step_id": "submission", "name": "工商提交", "order": 5, "agent_auto": False},
            {"step_id": "review", "name": "市监局审核", "order": 6, "agent_auto": False},
            {"step_id": "license_update", "name": "换发执照", "order": 7, "agent_auto": False},
        ],
    },
    "team_building": {
        "name": "团建策划",
        "description": "企业团队建设活动策划与执行。户外拓展、室内团建、主题工作坊等。AI根据团队人数、预算、偏好推荐最优方案。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "3-7",
        "price_range": "按方案报价",
        "capabilities": None,
    },
    "business_dining": {
        "name": "商务宴请",
        "description": "商务宴请一站式安排。餐厅推荐、菜单定制、包间预订、酒水搭配。AI根据接待规格、预算、口味偏好推荐。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "1-3",
        "price_range": "免费咨询",
        "capabilities": None,
    },
    "corporate_procurement": {
        "name": "企业采购",
        "description": "企业办公用品、设备、礼品等采购。比价后报价，透明中间价。AI根据需求自动比价推荐最优供应商。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "2-5",
        "price_range": "按需报价",
        "capabilities": None,
    },
    "logistics_delivery": {
        "name": "物流配送",
        "description": "企业物流配送服务。文件、包裹、货物等。对接多家运力，选最优方案。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "1-3",
        "price_range": "比价报价",
        "capabilities": None,
    },
    "sales_outsourcing": {
        "name": "销售外包",
        "description": "企业销售业务外包服务。电销、地推、渠道拓展等。按效果付费，免费需求匹配。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "视项目而定",
        "price_range": "按效果付费",
        "capabilities": None,
    },
    "third_party_operations": {
        "name": "代运营",
        "description": "企业新媒体/电商平台代运营。抖音、小红书、淘宝、京东等。免费方案推荐。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "月度服务",
        "price_range": "3000-20000/月",
        "capabilities": None,
    },
    "recruitment_outsourcing": {
        "name": "猎头/招聘外包",
        "description": "企业招聘外包服务。高端猎头、批量招聘、RPO。按结果收费。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "视职位而定",
        "price_range": "年薪15-25%",
        "capabilities": None,
    },
    "corporate_training": {
        "name": "企业培训",
        "description": "企业内训服务。管理培训、技能培训、团建培训等。免费比价，推荐最优讲师。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "按场次",
        "price_range": "5000-50000/场",
        "capabilities": None,
    },
    "manufacturing_sampling": {
        "name": "代工打样",
        "description": "工厂代工/打样/小批量生产。免费工厂匹配，按量报价。覆盖电子、服装、五金、塑料等行业。",
        "status": "planning",
        "schema_model": None,
        "estimated_days": "视产品而定",
        "price_range": "按量报价",
        "capabilities": None,
    },
}

VALID_TASK_TYPES = list(SERVICE_REGISTRY.keys())

# ═══════════════════════════════════════════════
# 超值定价 (v0.5.0, credits计价, 1 credit ≈ 1 RMB)
# ═══════════════════════════════════════════════

SERVICE_PRICING = {
    "company_registration": {"base_price": 499, "market_price": "699-1299", "cheap_reason": "流程标准化，AI预填+人工跑腿，比代记账公司便宜30%"},
    "high_tech_application": {"base_price": 5000, "market_price": "8000-30000", "cheap_reason": "评分预评估AI化，减少无效申报"},
    "ip_application": {"base_price": 599, "market_price": "800-8000", "cheap_reason": "查新和撰写AI辅助，降低人工成本"},
    "trademark": {"base_price": 299, "market_price": "800-1500/类", "cheap_reason": "AI查新+模板化，每类收费比市场省80%"},
    "import_export": {"base_price": 599, "market_price": "800-2500", "cheap_reason": "材料预审AI化，一次性通过率提升"},
    "legal_consulting": {"base_price": 199, "market_price": "200-30000", "cheap_reason": "AI初筛+律师终审，降低咨询门槛"},
    "accounting": {"base_price": 99, "market_price": "200/月", "cheap_reason": "票据OCR+AI记账，人工复核更低成本"},
    "tax_registration": {"base_price": 199, "market_price": "300-500", "cheap_reason": "AI预填+人工跑腿"},
    "bank_account": {"base_price": 299, "market_price": "300-800", "cheap_reason": "资料预审AI化，一次通过"},
    "license_application": {"base_price": 599, "market_price": "1000-5000", "cheap_reason": "材料AI预审，减少返工"},
    "company_change": {"base_price": 399, "market_price": "500-2000", "cheap_reason": "流程AI化，效率翻倍"},
    "team_building": {"base_price": 0, "market_price": "按方案报价", "cheap_reason": "免费咨询方案，按需求报价"},
    "business_dining": {"base_price": 0, "market_price": "免费咨询", "cheap_reason": "免费推荐，按消费结算"},
    "corporate_procurement": {"base_price": 0, "market_price": "按需报价", "cheap_reason": "比价后报价，透明中间价"},
    "logistics_delivery": {"base_price": 0, "market_price": "比价报价", "cheap_reason": "对接多家运力，选最优"},
    "sales_outsourcing": {"base_price": 0, "market_price": "按效果付费", "cheap_reason": "免费需求匹配，谈成收费"},
    "third_party_operations": {"base_price": 0, "market_price": "3000-20000/月", "cheap_reason": "免费方案推荐"},
    "recruitment_outsourcing": {"base_price": 0, "market_price": "年薪15-25%", "cheap_reason": "按结果收费"},
    "corporate_training": {"base_price": 0, "market_price": "5000-50000/场", "cheap_reason": "免费比价，推荐最优讲师"},
    "manufacturing_sampling": {"base_price": 0, "market_price": "按量报价", "cheap_reason": "免费工厂匹配"},
}
